// src/components/cmd.tsx
import React, { useEffect, useRef, useState } from "react";

import { removeWindow } from "./wm";
import { Config } from "../config/conf";
import { readDir } from "@tauri-apps/api/fs";
import { resolve } from "@tauri-apps/api/path";
import { commander } from "../command/cmd";

type Cmd = {
    config: Config;
    value?: string;
    text?: JSX.Element;
};


export const Cmd = ({ config, value, text }: Cmd) => {
    const dialog = useRef<HTMLDivElement>();
    const commandPrompt = useRef() as React.MutableRefObject<HTMLInputElement>;
    const [results, setRes] = useState(null);

    useEffect(() => {
        if (text) {
            setRes(text);
        }
    }, []);
    useEffect(() => {
        const handle = (e: KeyboardEvent) => {
            if (e.key == "Enter") {
                e.preventDefault();
                if (commandPrompt.current.value != undefined) {
                    commander(
                        commandPrompt.current.value,
                        dialog.current,
                        config,
                        setRes
                    );
                }
                window.document.removeEventListener("keyup", handle);
            }

            if (e.key == "Escape") {
                e.preventDefault();
                removeWindow("command");
                commandPrompt.current.parentElement?.remove();
            }
        };
        commandPrompt.current.addEventListener("keydown", handle);
        commandPrompt.current.focus();
    });

    return (
        <div>
            <div
                style={{
                    overflowWrap: "break-word",
                    background: "white",
                    borderRadius: "5px",
                    padding: "5px",
                }}
                ref={dialog}
            >
                {results != null ? results : ""}
            </div>
            <input
                placeholder="command"
                ref={commandPrompt}
                className="cmd"
                defaultValue={value}
                onInput={async (e) => {
                    const el = e.target as HTMLInputElement;
                    const d = dialog.current;
                    if (el.value.startsWith("o")) {
                        d.style.setProperty("border", "1px solid black");
                        const rawPath = el.value.split(" ")[1].trim();
                        const Path = await resolve(rawPath);
                        const items = await readDir(Path, {});
                        const list = items.map((c) => <p>{c.name}</p>);
                        setRes(<p id="">{list}</p>);
                    } else {
                        d.style.setProperty("border", "0px solid white");
                        setRes(null);
                    }
                }}
                style={{
                    width: "100%",
                    marginTop: "10px",
                    border: "none",
                    borderBottom: "1px solid black",
                    outline: "none",
                    background: "var(--cmd-bg-color)",
                    color: "var(--cmd-fg-color)",
                    ...config.cmd_theme.styles,
                }}
            />
        </div>
    );
};

// src/components/std/cmd.svelte
<script lang="ts">
    import hotkey from "hotkeys-js";
    import { onMount } from "svelte";
    import { removeWindow } from "../../editor/wm/main";
    import { config } from "../store";

    let value: string;
    let doc = "";
    let input: HTMLInputElement;

    let styleStrings: { body: string; input: string; doc: string } = {
        body: "",
        input: "",
        doc: "",
    };
    export let style: {
        body: Array<string>;
        input: Array<string>;
        doc: Array<string>;
    } = $config.cmd_theme || {
        body: ["color: black"],
        input: ["color: black"],
        doc: ["color: black"],
    };

    $: if (style["body"]) styleStrings["body"] = style["body"].join(";");

    $: if (style["input"]) styleStrings["input"] = style["input"].join(";");

    $: if (style["doc"]) styleStrings["doc"] = style["doc"].join(";");

    onMount(() => {
        hotkey("escape", () => {
            removeWindow("cmd");
        });
        input.focus();
    });

    const command = (arg: string, el: HTMLInputElement) => {
        if (arg.startsWith("echo")) {
            doc = arg.split(" ")[1];
        }
        el.value = "";
    };

    const handleIn = (e: KeyboardEvent) => {
        if (e.key == "Enter") {
            e.preventDefault();
            const el = e.target as HTMLInputElement;
            command(value, el);
        }
    };
</script>

<div
    style={styleStrings.body ? styleStrings.body : styleStrings.body + ";"}
    class="cmd-body"
>
    <div
        style={styleStrings.doc ? styleStrings.doc : styleStrings.doc + ";"}
        class="cmd-doc"
    >
        {doc}
    </div>
    <input
        style={styleStrings.input
            ? styleStrings.input
            : styleStrings.input + ";"}
        id="cmd"
        placeholder="command..."
        bind:value
        bind:this={input}
        on:keyup={handleIn}
        class="cmd-input"
    />
</div>

<style>
    .cmd-body {
        width: 100%;
        display: grid;
        grid-template-rows: inherit inherit;
        grid-template-columns: 100%;
        padding: 15px;
        height: fit-content;
        justify-items: center;

        color: black;
    }
    .cmd-input {
        width: 60%;
    }
    .cmd-doc {
        text-align: left;
        width: 60%;
        padding: 5px;
    }
</style>
