// src/components/menu.tsx
//@ts-nocheck
import "./menu.css";
import React from "react";
import { Editor } from "@tiptap/core";
import Select from "react-select";
import CreatableSelect from "react-select/creatable";

import FontSize from "./font-size";

const Header = (label: string, editor: Editor) => {
    const labelInt = parseInt(label);
    editor.commands.toggleHeading({ level: labelInt });
    return editor.isActive("heading", { level: labelInt }) ? "is-active" : "";
};
type BtnProps = {
    editor: Editor;
};
const Btns = ({ editor }: BtnProps) => {
    if (editor == null) {
        return <p></p>;
    }
    const customStyles = {
        control: (base: React.CSSProperties) => ({
            ...base,
            background: "#181818",
            color: "white",
            border: "0px solid black",
            boxShadow: null,
            borderColor: "black",
        }),
        menu: (base: React.CSSProperties) => ({
            ...base,
            width: "max-content",
            border: "0px solid black",
        }),
        input: (base: React.CSSProperties) => ({
            ...base,
            color: "white",
            border: "0px solid black",
        }),
        menuList: (base: React.CSSProperties, state) => ({
            ...base,
            color: "white",
            borderRadius: 5,
            background: state.isActive ? "#454545" : "#181818",
            border: "0px solid black",
        }),
        singleValue: (base: React.CSSProperties, state) => ({
            ...base,
            color: "white",
            background: state.isActive ? "#454545" : "#181818",
            border: "0px solid black",
        }),
        option: (base: React.CSSProperties, state) => ({
            ...base,
            color: "white",
            background:
                state.isFocused || state.isActive ? "#454545" : "#181818",
            border: "0px solid black",
        }),
    };

    const options = [
        { label: "Heading", value: "1" },
        { label: "sub-heading", value: "2" },
    ];
    const sizeOptions = [
        { label: "8", value: "8px" },
        { label: "9", value: "9px" },
        { label: "10", value: "10px" },
        { label: "11", value: "11px" },
        { label: "12", value: "12px" },
        { label: "14", value: "14px" },
        { label: "16", value: "16px" },
        { label: "18", value: "18px" },
        { label: "24", value: "24px" },
        { label: "30", value: "30px" },
        { label: "36", value: "36px" },
        { label: "48", value: "48px" },
        { label: "60", value: "60px" },
        { label: "72", value: "72px" },
        { label: "96", value: "96px" },
    ];
    FontSize.configure({
        types: ["textStyle"],
    });
    return (
        <div className="btn-nav">
            <button
                onClick={() => editor.chain().focus().toggleBold().run()}
                className={editor.isActive("bold") ? "is-active" : ""}
            >
                <b>B</b>
            </button>
            <button
                onClick={() => editor.chain().focus().toggleItalic().run()}
                className={editor.isActive("italic") ? "is-active" : ""}
            >
                <em>I</em>
            </button>

            <button
                onClick={() => editor.chain().focus().toggleBulletList().run()}
                className={editor.isActive("bulletList") ? "is-active" : ""}
            >
                bl
            </button>
            <button
                onClick={() => editor.chain().focus().toggleOrderedList().run()}
                className={editor.isActive("orderedList") ? "is-active" : ""}
            >
                ol
            </button>
            <CreatableSelect
                value={{
                    label: (() => {
                        if (editor.getAttributes("textStyle").size) {
                            let size = editor
                                .getAttributes("textStyle")
                                .size.split("px")[0];
                            return size;
                        }
                        return "16";
                    })(),
                }}
                styles={customStyles as any}
                onChange={(e: any) => {
                    editor.commands.setFontSize(e.value);
                }}
                className="header-dropdown"
                menuPlacement="top"
                options={sizeOptions}
                components={{
                    DropdownIndicator: () => null,
                    IndicatorSeparator: () => null,
                }}
            />
            <Select
                defaultValue={options[0]}
                styles={customStyles as any}
                onChange={(e) => {
                    e.Classname = Header(e.value, editor);
                }}
                className="header-dropdown"
                menuPlacement="top"
                options={options}
                components={{
                    DropdownIndicator: () => null,
                    IndicatorSeparator: () => null,
                }}
            />
        </div>
    );
};

//<select
//               defaultValue={options[0]}
//           styles={customStyles}
//               onChange={(e) => {
//                   e.Classname = Header(e.value, editor);
//               }}
//               className="header-dropdown"
//               menuPlacement="top"
//               options={options}
//               components={{
//                   DropdownIndicator: () => null,
//                   IndicatorSeparator: () => null,
//               }}
//           />
const Menu = ({ editor }) => {
    return (
        <div className="menu">
            <Btns editor={editor} />
        </div>
    );
};
export default Menu;

// src/components/Menu.svelte
<script lang="ts">
    import "./menu.css";
    import Select from "svelte-select";
    import Item from "./Item.svelte";
    import SizeItem from "./SizeItem.svelte";
    import {
        selectedItem,
        listOpen,
        size,
        sizeListOpen,
        lastHead,
    } from "./store";
    import FontSize from "../editor/fontsize";
    import { onMount } from "svelte";
    import type { EditorMain } from "../editor/editor";

    export let editor: EditorMain;
    const sizeVar = size;

    const Header = (label: 1 | 2) => {
        const pos = editor.state.selection.$anchor.pos;
        editor.commands.toggleHeading({ level: label });
        editor.commands.focus(pos);
        lastHead.update(() => true);
        return editor.isActive("heading", { level: label });
    };

    const options = [
        { label: "Heading", value: "1" },
        { label: "Sub Heading", value: "2" },
    ];
    const sizeOptions = [
        { label: "8", value: "8pt" },
        { label: "9", value: "9pt" },
        { label: "10", value: "10pt" },
        { label: "11", value: "11pt" },
        { label: "12", value: "12pt" },
        { label: "14", value: "14pt" },
        { label: "16", value: "16pt" },
        { label: "18", value: "18pt" },
        { label: "24", value: "24pt" },
        { label: "30", value: "30pt" },
        { label: "36", value: "36pt" },
        { label: "48", value: "48pt" },
        { label: "60", value: "60pt" },
        { label: "72", value: "72pt" },
        { label: "96", value: "96pt" },
    ];
    FontSize.configure({
        types: ["textStyle"],
    });
    size.subscribe((e) => {
        if (editor && e.transform) {
            editor.commands.setFontSize(e.value);
        }
    });
    selectedItem.subscribe((e) => {
        if (e && editor) {
            Header(parseInt(e.value) as 1 | 2);
        }
    });
    $: if (editor && editor.getAttributes("textStyle").size != $size.value) {
        const size = editor.getAttributes("textStyle").size;
        if (size != undefined) {
            sizeVar.update(() => {
                return {
                    label: `${size.replace("pt", "")}`,
                    value: `${size}`,
                    transform: false,
                };
            });
            if (editor.getAttributes("heading").level == 1) {
                sizeVar.update(() => {
                    return { label: `24`, value: `24pt`, transform: true };
                });
            }
        } else {
            if (editor.getAttributes("heading").level == 1) {
                sizeVar.update(() => {
                    return { label: `24`, value: `24pt`, transform: true };
                });
            }
            if (editor.getAttributes("heading").level == 2) {
                sizeVar.update(() => {
                    return { label: `18`, value: `18pt`, transform: true };
                });
            }
        }
    }
</script>

{#if editor}
    <div class="btn-nav">
        <button
            on:click={() => editor.chain().focus().toggleBold().run()}
            class:active={editor.isActive("bold")}
        >
            <b>B</b>
        </button>
        <button
            on:click={() => editor.chain().focus().toggleItalic().run()}
            class:active={editor.isActive("italic")}
        >
            <em>I</em>
        </button>

        <button
            on:click={() => editor.chain().focus().toggleBulletList().run()}
            class:active={editor.isActive("bulletList")}
        >
            bl
        </button>
        <button
            on:click={() => editor.chain().focus().toggleOrderedList().run()}
            class:active={editor.isActive("orderedList")}
        >
            ol
        </button>

        <Select
            items={options}
            isClearable={false}
            bind:value={$selectedItem}
            bind:listOpen={$listOpen}
            {Item}
        />
        <Select
            items={sizeOptions}
            isClearable={false}
            Item={SizeItem}
            bind:value={$size}
            bind:listOpen={$sizeListOpen}
        />
    </div>
{/if}
